# Generated by Django 4.1.3 on 2022-11-14 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('is_right', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='questionImages')),
                ('description', models.TextField(max_length=5000)),
                ('authors', models.ManyToManyField(blank=True, related_name='compiled_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuestionResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_choices', models.ManyToManyField(blank=True, related_name='question_resaults_right', to='quiz.answer')),
                ('user_choices', models.ManyToManyField(blank=True, related_name='question_resaults_user', to='quiz.answer')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопрос',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Высшая сатематика', max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('theory', models.TextField(blank=True, null=True)),
                ('success_percent', models.FloatField(default=50.0)),
                ('allotted_time', models.PositiveIntegerField(default=10)),
                ('attempts_number', models.PositiveIntegerField(default=3)),
                ('at_start', models.DateTimeField(blank=True, null=True)),
                ('at_finish', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='compiled_tests', to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(related_name='tests', to='quiz.course')),
                ('questions', models.ManyToManyField(related_name='test', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(blank=True, default=False, null=True)),
                ('question_resaults', models.ManyToManyField(blank=True, to='quiz.questionresault')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='quiz.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат Теста',
                'verbose_name_plural': 'Результаты Теста',
            },
        ),
        migrations.CreateModel(
            name='courseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.group')),
            ],
            options={
                'verbose_name': 'Курс-Группа',
                'verbose_name_plural': 'Курсы-Группы',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(related_name='courses', through='quiz.courseGroup', to='profiles.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='author_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
    ]
