# Generated by Django 4.1.3 on 2022-11-06 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_group_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.cource')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.group')),
            ],
        ),
        migrations.AddField(
            model_name='cource',
            name='groups',
            field=models.ManyToManyField(related_query_name='cources', through='quiz.CourceGroup', to='profiles.group'),
        ),
        migrations.AddField(
            model_name='cource',
            name='teachers',
            field=models.ManyToManyField(related_query_name='author_courses', to='profiles.profile'),
        ),
    ]
