# Generated by Django 4.1.3 on 2022-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
