# Generated by Django 4.1.3 on 2022-11-07 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_group'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cource',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='courcegroup',
            options={'verbose_name': 'Курс-Группа', 'verbose_name_plural': 'Курсы-Группы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='at_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='at_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Высшая сатематика', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='theory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cource',
            name='groups',
            field=models.ManyToManyField(related_name='cources', through='quiz.CourceGroup', to='profiles.group'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='author_courses', to='profiles.profile'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='questionImages')),
                ('description', models.TextField(max_length=5000)),
                ('authors', models.ManyToManyField(related_name='compiled_questions', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('is_right', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='authors',
            field=models.ManyToManyField(related_name='compiled_tests', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='test', to='quiz.question'),
        ),
    ]
