# Generated by Django 4.1.3 on 2022-11-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresault',
            name='question_resaults',
        ),
        migrations.RemoveField(
            model_name='testresault',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresault',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionResault',
        ),
        migrations.DeleteModel(
            name='TestResault',
        ),
    ]
