# Generated by Django 4.1.3 on 2022-11-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_group'),
        ('quiz', '0004_test_success_percent_alter_answer_is_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='authors',
            field=models.ManyToManyField(related_name='compiled_tests', to='profiles.profile'),
        ),
    ]
