# Generated by Django 4.1.3 on 2022-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_email_profile_unique_email_profile'),
        ('quiz', '0006_test_cources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='compiled_tests', to='profiles.profile'),
        ),
    ]
