# Generated by Django 4.1.3 on 2022-11-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_email_profile_unique_email_profile'),
        ('quiz', '0008_test_allotted_time_test_attempts_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_choices', models.ManyToManyField(blank=True, related_name='question_resaults_right', to='quiz.answer')),
                ('user_choices', models.ManyToManyField(blank=True, related_name='question_resaults_user', to='quiz.answer')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопрос',
            },
        ),
        migrations.CreateModel(
            name='TestResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(blank=True, default=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_results', to='profiles.profile')),
                ('question_resaults', models.ManyToManyField(blank=True, to='quiz.questionresault')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='quiz.test')),
            ],
            options={
                'verbose_name': 'Результат Теста',
                'verbose_name_plural': 'Результаты Теста',
            },
        ),
    ]
