# Generated by Django 4.1.3 on 2022-11-24 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_remove_testresault_question_resaults_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='quiz.question')),
                ('right_choices', models.ManyToManyField(blank=True, related_name='question_resaults_right', to='quiz.answer')),
                ('user_choices', models.ManyToManyField(blank=True, related_name='question_resaults_user', to='quiz.answer')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопрос',
            },
        ),
        migrations.CreateModel(
            name='TestResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(verbose_name='Сейчас выполняется')),
                ('passed', models.BooleanField(blank=True, default=False, null=True)),
                ('question_resaults', models.ManyToManyField(blank=True, to='certification.questionresault')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='quiz.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат Теста',
                'verbose_name_plural': 'Результаты Теста',
            },
        ),
    ]
