# Generated by Django 4.1.3 on 2022-12-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='quiz.test'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='right_choices',
            field=models.ManyToManyField(blank=True, related_name='question_resaults_right', to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='user_choices',
            field=models.ManyToManyField(blank=True, related_name='question_resaults_user', to='quiz.answer'),
        ),
    ]
