# Generated by Django 4.1.3 on 2022-11-06 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('А', 'Ракетно-космической техники'), ('Е', 'Оружие и системы вооружения'), ('И', 'Информационные и управляющие системы'), ('О', 'Естественнонаучный'), ('Р', 'Международного менеджмента')], default='А', max_length=1)),
                ('number', models.CharField(default='000', max_length=3)),
                ('study_form', models.CharField(choices=[('Б', 'Бакалавриат'), ('С', 'Специалитет'), ('М', 'Магистратура')], default='Б', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='profiles', to='profiles.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
