# Generated by Django 4.1.3 on 2022-11-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_group_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(default='000', max_length=3, unique=True),
        ),
    ]
