# Generated by Django 4.1.3 on 2022-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_form',
            field=models.CharField(choices=[('Б', 'Бакалавриат'), ('С', 'Специалитет'), ('М', 'Магистратура'), ('П', 'Повыгение квалификации')], default='Б', max_length=1),
        ),
    ]
